# Generated by Django 5.0.2 on 2024-03-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_panelconnection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_login_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
