# Generated by Django 5.0.2 on 2024-02-21 04:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_title',
            field=models.CharField(max_length=512, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_link',
            field=models.TextField(max_length=512, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
    ]
