# Generated by Django 5.0.2 on 2024-02-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscription_subscription_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expose',
            field=models.BooleanField(default=False),
        ),
    ]
